config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :singers
  resources :songs
  resources :types
  resources :clients
  root "clients#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :api, defaults: { format: :json } do
    resources :types
    resources :singers
    resources :users
    post 'login' => 'auth#login'
    put 'login' => 'auth#login'
    patch 'login' => 'auth#login'
  end
  
  get '/dashboards', to: 'dashboards#index'
  
end

app/models/singer.rb
class Singer < ApplicationRecord
  enum genre: { nam: false, nu: true }
  has_many :songs
  has_one_attached :avatar
end

app/controllers/api/singers_controller.rb
class Api::SingersController < ApplicationController
  include ActiveStorage::SetCurrent
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_singer, only: [:show]

  def index
    singers = Singer.all
    render json: singers, each_serializer: Api::SingerSerializer
  end

  def show
    render json: @singer, serializer: Api::SingerWithSongsSerializer
  end


  private
  def set_singer
    @singer = Singer.find(params[:id])
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  before_action :set_singer, only: %i[ show edit update destroy ]

  # GET /singers or /singers.json
  def index
    @singers = Singer.all
  end

  # GET /singers/1 or /singers/1.json
  def show
  end

  # GET /singers/new
  def new
    @singer = Singer.new
  end

  # GET /singers/1/edit
  def edit
  end

  # POST /singers or /singers.json
  def create
    @singer = Singer.new(singer_params)

    respond_to do |format|
      if @singer.save
        format.html { redirect_to singers_url, notice: "Singer was successfully created." }
        format.json { render :show, status: :created, location: @singer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
    flash[:notice] = "Singer was successfully created."
  end

  # PATCH/PUT /singers/1 or /singers/1.json
  def update
    respond_to do |format|
      if @singer.update(singer_params)
        format.html { redirect_to singers_url, notice: "Singer was successfully updated." }
        format.json { render :show, status: :ok, location: @singer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @singer.errors, status: :unprocessable_entity }
      end
    end
    flash[:notice] = "Singer was successfully updated."
  end

  # DELETE /singers/1 or /singers/1.json
  def destroy
    @singer.destroy

    respond_to do |format|
      format.html { redirect_to singers_url, notice: "Singer was successfully destroyed." }
      format.json { head :no_content }
    end
    flash[:notice] = "Singer was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_singer
      @singer = Singer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def singer_params
      params.require(:singer).permit(:name, :genre, :description, :avatar)
    end
end

app/helpers/api/singers_helper.rb
module Api::SingersHelper
end

app/helpers/singers_helper.rb
module SingersHelper
end

app/views/singers/_form.html.erb
<div class="d-flex justify-content-center" style="min-height: 100vh;">
  <div class="col-md-6 mx-auto">
    <%= form_with(model: singer) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
      </div>

      <%= form.file_field :avatar %>

     
      <div class="form-group">
        <label for="gender">Giới tính:</label><br>
        <%= form.radio_button :genre, :nam %>
        <%= form.label :nam, 'Nam' %>
        <%= form.radio_button :genre, :nu %>
        <%= form.label :nu, 'Nữ' %>
      </div>


     <div class="form-group">
        <%= form.submit class: "btn btn-primary", style: "margin-top: 10px;" %>
        <%= link_to "Back to singers", singers_path, class: "btn btn-danger", style: "margin-top: 10px; margin-left: 10px;" %>
      </div>
    <% end %>
  </div>
</div>


<style>
  .gender-radio {
    display: inline-block; 
    margin-right: 10px;  
  }
</style>

app/views/singers/_singer.html.erb
<div id="<%= dom_id singer %>">
</div>

app/views/singers/edit.html.erb
<h2 class="mt-2" style="text-align: center">Editing singer</h2>
<%= render "form", singer: @singer %>

app/views/singers/index.html.erb
<h2 class="mt-2" style="text-align: center">Singers</h2>
<div style="text-align: right; margin-top: 20px; margin-right:17%">
  <%= link_to "New Singer", new_singer_path, class: "btn btn-primary" %>
</div>
<table class="table table-borderless">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @singers.each do |singer| %>
      <tr>
        <td><%= singer.name %></td>
        <td><%= singer.description %></td>
        <td>
          <%= link_to edit_singer_path(singer) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </td>
        <td>
         <%= link_to singer_path(singer), method: :delete do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<style>
  /* Để căn giữa bảng */
  table.table-borderless {
    width: 70%; /* Tổng chiều rộng của bảng là 70% */
    margin: 0 auto;
  }

  /* Thiết lập lề trái và lề phải cho mỗi cột */
  table.table-borderless th,
  table.table-borderless td {
    padding: 10px; /* Để tạo khoảng cách bên trong các ô */
    margin-left: 2%; /* Lề trái của mỗi cột là 2% */
    margin-right: 2%; /* Lề phải của mỗi cột là 2% */
  }

  /* Thiết lập kích thước cho từng cột */
  table.table-borderless th:nth-child(2),
  table.table-borderless td:nth-child(2) {
    width: 50%; /* Kích thước của cột 2 là 25% */
  }

  table.table-borderless th:nth-child(4),
  table.table-borderless td:nth-child(4) {
    width: 10%; /* Kích thước của cột 4 là 10% */
  }

  table.table-borderless th:nth-child(3),
  table.table-borderless td:nth-child(3) {
    width: 10%; /* Kích thước của cột 5 là 10% */
  }
</style

app/views/singers/new.html.erb
<h1 class="mt-2" style="text-align: center">New singer</h1>

<%= render "form", singer: @singer %>

app/views/singers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @singer %>

<div>
  <%= link_to "Edit this singer", edit_singer_path(@singer) %> |
  <%= link_to "Back to singers", singers_path %>

  <%= button_to "Destroy this singer", @singer, method: :delete %>
</div>