config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :singers
  resources :songs
  resources :types
  resources :clients
  root "clients#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :api, defaults: { format: :json } do
    resources :types
    resources :singers
    resources :users
    post 'login' => 'auth#login'
    put 'login' => 'auth#login'
    patch 'login' => 'auth#login'
  end
  
  get '/dashboards', to: 'dashboards#index'
  
end

app/controllers/api/types_controller.rb
class Api::TypesController < ApplicationController
  include ActiveStorage::SetCurrent
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :set_type, only: [:show]

  def index
    types = Type.all
    render json: types, each_serializer: Api::TypeSerializer
  end

  def show
    render json: @type, serializer: Api::TypeWithSongsSerializer
  end


  private
  def set_type
    @type = Type.find(params[:id])
  end


end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_url, notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
    flash[:notice] = "Type was successfully created."
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to types_url, notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
    flash[:notice] = "Type was successfully updated."
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
      flash[:notice] = "Type was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name, :description, :popularity, :image)
    end
end

app/helpers/api/types_helper.rb
module Api::TypesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<div class="d-flex justify-content-center" style="min-height: 100vh;">
  <div class="col-md-6 mx-auto">
    <%= form_with(model: type) do |form| %>
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_field :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :popularity %>
        <%= form.number_field :popularity, class: "form-control" %>
      </div>
      
      <%= form.file_field :image %>

      <div class="form-group">
        <%= form.submit class: "btn btn-primary", style: "margin-top: 10px;" %>
        <%= link_to "Back to types", types_path, class: "btn btn-danger", style: "margin-top: 10px; margin-left: 10px;" %>
      </div>


    <% end %>
  </div>
</div>

app/views/types/_type.html.erb
<div id="<%= dom_id type %>">
</div>

app/views/types/edit.html.erb
<h2 class="mt-2" style="text-align: center">Editing type</h2>


<%= render "form", type: @type %>

<br>

app/views/types/index.html.erb
<h2 class="mt-2" style="text-align: center">Types</h2>
<div style="text-align: right; margin-top: 20px; margin-right:17%">
  <%= link_to "New Type", new_type_path, class: "btn btn-primary" %>
</div>


<table class="table table-borderless">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Popularity</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.description %></td>
        <td><%= type.popularity %></td>
        <td>
          <%= link_to edit_type_path(type) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </td>
        <td>
         <%= link_to type_path(type), method: :delete do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<style>
  /* Để căn giữa bảng */
  table.table-borderless {
    width: 70%; /* Tổng chiều rộng của bảng là 70% */
    margin: 0 auto;
  }

  /* Thiết lập lề trái và lề phải cho mỗi cột */
  table.table-borderless th,
  table.table-borderless td {
    padding: 10px; /* Để tạo khoảng cách bên trong các ô */
    margin-left: 2%; /* Lề trái của mỗi cột là 2% */
    margin-right: 2%; /* Lề phải của mỗi cột là 2% */
  }

  /* Thiết lập kích thước cho từng cột */
  table.table-borderless th:nth-child(2),
  table.table-borderless td:nth-child(2) {
    width: 30%; /* Kích thước của cột 2 là 25% */
  }

  table.table-borderless th:nth-child(3),
  table.table-borderless td:nth-child(3) {
    width: 30%; /* Kích thước của cột 3 là 25% */
  }

  table.table-borderless th:nth-child(4),
  table.table-borderless td:nth-child(4) {
    width: 10%; /* Kích thước của cột 4 là 10% */
  }

  table.table-borderless th:nth-child(5),
  table.table-borderless td:nth-child(5) {
    width: 10%; /* Kích thước của cột 5 là 10% */
  }
</style

app/views/types/new.html.erb
<h1 class="mt-2" style="text-align: center">New type</h1>

<%= render "form", type: @type %>

app/views/types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @type %>

<div>
  <%= link_to "Edit this type", edit_type_path(@type) %> |
  <%= link_to "Back to types", types_path %>

  <%= button_to "Destroy this type", @type, method: :delete %>
</div>