config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :singers
  resources :songs
  resources :types
  resources :clients
  root "clients#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :api, defaults: { format: :json } do
    resources :types
    resources :singers
    resources :users
    post 'login' => 'auth#login'
    put 'login' => 'auth#login'
    patch 'login' => 'auth#login'
  end
  
  get '/dashboards', to: 'dashboards#index'
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :set_client, only: %i[ show edit update destroy ]
  
    def index
      @clients = User.where(role: true)
    end
  
    def show
    end
  
    def new
      @client = User.new
    end
  
    def edit
    end
  
    # POST /singers or /singers.json
    def create
      byebug
      @client = User.new(client_params_create)
      @client.active = 1
      @client.role = 1
      
      respond_to do |format|
        if @client.save
          format.html { redirect_to clients_url, notice: "Client was successfully created." }
          format.json { render :show, status: :created, location: @client }
          flash[:notice] = "Client was successfully created."
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @client.errors, status: :unprocessable_entity }
          flash[:notice] = "Client was fail created."
        end
      end
      
    end
  
    # PATCH/PUT /singers/1 or /singers/1.json
    def update
      respond_to do |format|
        if params[:change_client_password].present?
          if @client.update(client_params_password)
            format.html { redirect_to clients_url, notice: "Client was successfully updated password." }
            format.json { render :show, status: :ok, location: @client }
            flash[:notice] = "Client was successfully updated password."
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @client.errors, status: :unprocessable_entity }
            flash[:notice] = "Client was successfully updated fail."
          end
        else
          if @client.update(client_params)
            format.html { redirect_to clients_url, notice: "Client was successfully updated information." }
            format.json { render :show, status: :ok, location: @client }
            flash[:notice] = "Client was successfully updated information."
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @client.errors, status: :unprocessable_entity }
            flash[:notice] = "Client was successfully updated fail."
          end
        end
        
      end
      
    end
  
    # DELETE /singers/1 or /singers/1.json
    def destroy
      # @singer.destroy
  
      # respond_to do |format|
      #   format.html { redirect_to singers_url, notice: "Singer was successfully destroyed." }
      #   format.json { head :no_content }
      # end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_client
        @client = User.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def client_params
        params.require(:user).permit(:email, :first_name, :last_name, :phone, :avatar)
      end

      def client_params_create
        params.require(:user).permit(:email, :first_name, :last_name, :phone, :avatar, :password, :password_confirmation)
      end

      def client_params_password
        params.require(:user).permit(:password, :password_confirmation)
      end


  
end

app/views/clients/_client.html.erb
<div id="<%= dom_id singer %>">
</div>

app/views/clients/_form.html.erb
<div class="d-flex justify-content-center" style="min-height: 100vh;">
  <div class="col-md-6 mx-auto">
    <%= form_with(model: @client, url: @client.new_record? ? clients_path : client_path(@client), method: @client.new_record? ? :post : :patch) do |form| %>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", readonly: !@client.new_record?, type: "email" %>
      </div>

      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "form-control", required: @client.new_record? %>
      </div>

      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "form-control", required: @client.new_record? %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, class: "form-control", required: @client.new_record? %>
      </div>

      <div class="form-group">
        <%= form.label :avatar, "Avatar" %>
        <%= form.file_field :avatar, class: "form-control", required: @client.new_record? %>
      </div>
      <% unless form.object.new_record?  %>
      <div class="form-group">
        <%= form.submit "Change Information", class: "btn btn-primary", style: "margin-top: 10px;" %>
      </div>
      <% end %>
      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", required: @client.new_record? %>
      </div>

      <div class="form-group">
        <%= form.label :password_confirmation, "Confirm Password" %>
        <%= form.password_field :password_confirmation, class: "form-control", required: @client.new_record? %>
      </div>
      <% unless form.object.new_record?  %>
      <div class="form-group">
        <%= form.submit "Change Password", :name => 'change_client_password', class: "btn btn-primary", style: "margin-top: 10px;" %>
        <%= link_to "Back to clients", clients_path, class: "btn btn-danger", style: "margin-top: 10px; margin-left: 10px;" %>
      </div>
      <% else %>
      <div class="form-group">
        <%= form.submit "Create", class: "btn btn-primary", style: "margin-top: 10px;" %>
        <%= link_to "Back to clients", clients_path, class: "btn btn-danger", style: "margin-top: 10px; margin-left: 10px;" %>
      </div>
      <% end %>


    <% end %>
  </div>
</div>



<style>
  .gender-radio {
    display: inline-block; 
    margin-right: 10px;  
  }
</style>

app/views/clients/edit.html.erb
<h2 class="mt-2" style="text-align: center">Editing client</h2>
<%= render "form", user: @user %>

app/views/clients/index.html.erb
<h2 class="mt-2" style="text-align: center">Clients</h2>
<div style="text-align: right; margin-top: 20px; margin-right:17%">
  <%= link_to "New Client", new_client_path, class: "btn btn-primary" %>
</div>
<table class="table table-borderless">
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Active</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @clients.each do |client| %>
      <tr>
        <td><%= client.email %></td>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.phone %></td>
        <td><%= client.active %></td>
        <td>
          <%= link_to edit_client_path(client) do %>
            <i class="fas fa-edit"></i>
          <% end %>
        </td>
        <td>
          <%= form_for client, url: client_path(client), method: :delete do |f| %>
            <%= f.submit "Delete" %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<style>
  /* Để căn giữa bảng */
  table.table-borderless {
    width: 70%; /* Tổng chiều rộng của bảng là 70% */
    margin: 0 auto;
  }

  /* Thiết lập lề trái và lề phải cho mỗi cột */
  table.table-borderless th,
  table.table-borderless td {
    padding: 10px; /* Để tạo khoảng cách bên trong các ô */
    margin-left: 2%; /* Lề trái của mỗi cột là 2% */
    margin-right: 2%; /* Lề phải của mỗi cột là 2% */
  }

  /* Thiết lập kích thước cho từng cột */
  table.table-borderless th:nth-child(2),
  table.table-borderless td:nth-child(2) {
    width: 15%; /* Kích thước của cột 2 là 25% */
  }

  table.table-borderless th:nth-child(4),
  table.table-borderless td:nth-child(4) {
    width: 15%; /* Kích thước của cột 4 là 10% */
  }

  table.table-borderless th:nth-child(3),
  table.table-borderless td:nth-child(3) {
    width: 15%; /* Kích thước của cột 5 là 10% */
  }

  table.table-borderless th:nth-child(5),
  table.table-borderless td:nth-child(5) {
    width: 10%; /* Kích thước của cột 4 là 10% */
  }

  table.table-borderless th:nth-child(6),
  table.table-borderless td:nth-child(6) {
    width: 10%; /* Kích thước của cột 4 là 10% */
  }
</style

app/views/clients/new.html.erb
<h1 class="mt-2" style="text-align: center">New clients</h1>

<%= render "form", client: @client %>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this singer", edit_client_path(@client) %> |
  <%= link_to "Back to singers", clients_path %>

  <%= button_to "Destroy this singer", @client, method: :delete %>
</div>