config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :singers
  resources :songs
  resources :types
  resources :clients
  root "clients#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  namespace :api, defaults: { format: :json } do
    resources :types
    resources :singers
    resources :users
    post 'login' => 'auth#login'
    put 'login' => 'auth#login'
    patch 'login' => 'auth#login'
  end
  
  get '/dashboards', to: 'dashboards#index'
  
end

app/views/layouts/_header.html.erb
<div class="d-flex justify-content-center" style="width:100%;background-color: rgba(0, 0, 0, 0.5); color: white;">
<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
    
    <%= link_to "OU Music", clients_path, class: "navbar-brand", "aria-current": "page" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
         <%= link_to "Client", clients_path, class: "nav-link #{'active' if current_page?(clients_path)}", "aria-current": "page" %>

        </li>
        <li class="nav-item">
         <%= link_to "Song", songs_path, class: "nav-link #{'active' if current_page?(songs_path)}", "aria-current": "page" %>

        </li>
        <li class="nav-item">
        <%= link_to "Type", types_path, class: "nav-link #{'active' if current_page?(types_path)}", "aria-current": "page" %>

        </li>
        <li class="nav-item">
        <%= link_to "Singer", singers_path, class: "nav-link #{'active' if current_page?(singers_path)}", "aria-current": "page" %>

        </li>
        <li class="nav-item">
        <%= link_to "Dashboard", dashboards_path, class: "nav-link #{'active' if current_page?(dashboards_path)}", "aria-current": "page" %>

        </li>
       
      </ul>
    </div>
  </div>
  <div class="col" style="height: 100%">
    <div class="">
      <%= button_to "Logout", destroy_user_session_path, method: :delete, style: "color: black; font-size: 20px", class: "btn btn-small btn-primary mx-2" %>
          

    </div>
  </div>
</nav>
</div>

<style>
.nav-link.active {
  background-color: #6ba6c9; /* Điền mã màu xanh nhạt bạn muốn ở đây */
  color: white;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
  </head>

  <body>
    <div class="container-fluid" style=" text-align:center;" >
      <% combined_alerts = [notice, alert].compact.join('<br/>').html_safe %>
      <% if combined_alerts.present? %>
        <div class="alert" style="padding-top: 0px; padding-bottom: 0px; margin-bottom: 0px;">
          <%= combined_alerts %>
        </div>
      <% end %>
    </div>
 <% if user_signed_in? %> 
   <%= render 'layouts/header' %>
  <% end %>
 

    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</html>